name: Learn How to Code
email: contact@learnhowtocode.in
github: https://github.com/recarreira/learnhowtocode.in

## Authors
authors:
  -
    name: Renata Carreira
    site: http://renatacarreira.com
    github: https://github.com/recarreira
  -
    name: Roberto Soares
    site: http://robertosoares.me
    github: https://github.com/roberto

## What we cover
languages: [ruby, python]
frameworks: [rails, django]

## Extra configs
pygments: false
exclude: [README.md,]
paginate: 1
